seed: 42
test_only: False
accelerator: "cpu"

data:
  data_dir: "data/data_file"
  data_loader: "dataloader"
  train_ratio: 0.8
  val_ratio: 0.1
  test_ratio: 0.1
  num_workers: 4
  augment: False
  image_size: 256
  noise_ratio: 0.4

wandb:
  project_name: ""
  run_name: ""
  experiment_id: "1"
  ex_description: ""

model:
  in_channels: 1
  batch_size: 1
  model_name: ""
  hidden_dim: 128
  embedding_size: 128
  accuracy_metric: "mse"
  coef: 1e-5
  coef1: 5e-5 
  coef2: 2e-4.
  ln_param: 1 

optimizer:
  optimizer: "adamw"
  lr: 3e-5
  weight_decay: 0.002
  momentum: 0.9
  betas: [0.9, 0.999]

scheduler:
  scheduler: "plateau"
  step_size: 30
  step_size_up: 1000
  patience: 2
  factor: 0.5
  min_lr: 3e-5
  max_lr: 5e-5
  T_max: 10
  gamma: 0.1

trainer:
  num_nodes: 1
  devices: 1
  max_epochs: 10
  log_dir: "./logs"
  log_every_n_steps: 2
  load_path: ""
  resume_from: False 
  checkpoint_dir: "./checkpoints/CHECKPOINT_DIR/"
  wandb_logging: False

test: 
  load_path: "./checkpoints/CHECKPOINT_FILE"
